/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/em0zPg6gRvh
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { getScopedI18n, getI18n } from "@/locales/server";
import Link from "next/link";
import {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuLink,
} from "@/components/ui/navigation-menu";
import { SwitchTheme } from "./swith-theme";
import { JSX, SVGProps } from "react";
import { TitlePage } from "./title-page";
import { DateComponent } from "./date-component";
import AnimatedGradientTextDemo from "./animated-gradient";

export default async function ContainerPage() {
  const t = await getI18n();

  return (
    <div className="flex min-h-screen flex-col bg-secondary">
      <header className="sticky top-0 z-40 w-full border-b bg-secondary/30">
        <div className="container flex h-16 items-center justify-between px-4 md:px-6">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 64 64"
            className="w-10 h-10"
          >
            <style type="text/css" id="dark-mode-сustom-style" />
            <style type="text/css" id="dark-mode-theme-changer-style" />
            <defs fill="#2D9964" />
            <path
              d="m35,12c0-3.09,1.91-5,5-5s5,1.91,5,5-1.91,5-5,5-5-1.91-5-5Zm6.51,16.74c1.97,2.34,4.43,5.26,10.49,5.26v-5c-3.74,0-4.9-1.38-6.67-3.48-2.07-2.46-4.65-5.52-11.33-5.52-9.65,0-15.18,5.13-19,12.76l4.47,2.24c2.77-5.54,5.71-8.34,9.74-9.43l-4.95,9.9c-1.89,3.79-4.71,5.53-8.94,5.53h-4.32v6h4.32c6.7,0,11.19-2.74,14.21-8.66,2.64,2,10.54,8.63,12.77,17.66l5.69-1.9c-2.21-8.96-8.54-15.45-12.63-18.85l4.26-8.51c.66.57,1.24,1.25,1.88,2.01Z"
              fill="#2D9964"
            />
          </svg>
        </div>
      </header>
      <main className="container mx-auto my-12 flex max-w-3xl flex-1 flex-col items-center px-4 md:px-6">
        <article className="space-y-4 prose prose-gray dark:prose-invert">
          <TitlePage>{t("title")}</TitlePage>
          {/* API de datas dou um timeSprint no em um db  */}
          <DateComponent>{t("date")}null data </DateComponent>

          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil, a
            possimus rerum natus suscipit voluptatum numquam amet, esse odio
            perferendis porro enim cupiditate ipsam rem fugiat aliquid aliquam
            ut eveniet!
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. A impedit
            corporis libero dignissimos, quam quae quasi earum facilis explicabo
            magni eius, ullam nostrum iure illo est dolorum consequuntur, nobis
            excepturi!
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit minus
            accusantium beatae quae consequatur molestias ab quaerat, enim
            deserunt aliquam vitae! Perferendis dignissimos deserunt molestiae
            accusantium odio soluta, neque ipsam! Lorem ipsum dolor sit amet
            consectetur adipisicing elit. Velit minus accusantium beatae quae
            consequatur molestias ab quaerat, enim deserunt aliquam vitae!
            Perferendis dignissimos deserunt molestiae accusantium odio soluta,
            neque ipsam!
          </p>
          <blockquote>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur,
            saepe sit nesciunt totam magnam ab distinctio libero laborum
            asperiores veritatis impedit non voluptatibus, modi enim obcaecati
            quaerat omnis repudiandae sunt.
          </blockquote>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est
            praesentium eligendi consequuntur autem magnam, non perspiciatis,
            porro placeat reprehenderit provident vel, molestiae harum nisi
            voluptates minima ullam beatae aliquam repellendus!
          </p>
        </article>
      </main>
      <footer className="bg-muted p-6 md:py-12 w-full">
        <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
          <div className="grid gap-1">
            <h3 className="font-semibold">Company</h3>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Products</h3>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Resources</h3>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Legal</h3>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Contact</h3>
          </div>
        </div>
      </footer>
    </div>
  );
}

function CalendarIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  );
}
